extensions:
  dx/excshell/1:
    operations:
      view:
        - type: web
          impl: index.html
    runtimeManifest:
      packages:
        __APP_PACKAGE__:
          license: Apache-2.0
          actions:
            assets-collection:
              function: actions/assets-collection/index.js
              web: 'yes'
              runtime: 'nodejs:14'
              inputs:
                LOG_LEVEL: debug
              annotations:
                require-adobe-auth: false
                final: true
            assets-thumbnail:
              function: actions/assets-thumbnail/index.js
              web: 'yes'
              runtime: 'nodejs:14'
              inputs:
                LOG_LEVEL: debug
              annotations:
                require-adobe-auth: false
                final: true
